language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -e ."
# command to run tests
script: cd ./tests && nosetests --nologcapture
